### ISSUE TITLE
Exact timing of parameters

### ISSUE THREAD

**Issue by Mv77** [matthew-zahn/CGMPort#5]
The code is currently very sloppy about what entry of SurvProbVec and PermGroFac applies to what period.

In fact I just messed with their length until HARK stopped throwing errors at me.

We need to figure out *exactly* how they work.

E.g. "Is PermGroFac[3] the growth rate from 2 to 3 or from 3 to 4", and the same for SurvProbVec.

A puzzle for me is that if I create an agent that lives for 3 periods HARK requires PermGroFac to be of length 3. In my mind it should be only 2: growth from 1 to 2 and from 2 to 3. We need to figure out why this is so.

**Comment by matthew-zahn** [comment]
From [ConsIndShockModel.py](https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsIndShockModel.py), which is an underlying tool called within ConsPortfolioModel.py, LivProb is defined as "Survival probability; likelihood of being alive at the beginning of the succeeding period" (see lines 367-368). Following your example, LivProb[3] is the probability of surviving into period 4 (conditional on surviving to period 3). 

This description aligns with the description of the data series from the paper and its use elsewhere in HARK. The SurvProbVec is used to create an effective discount rate for each period (DiscFac*LivProb see line 1034 of [ConsPortfolioModel.py](https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsPortfolioModel.py). Each row is associated with a given period (i.e., row 1 determines period 1 values). 

Again from [ConsIndShockModel.py](https://github.com/econ-ark/HARK/blob/master/HARK/ConsumptionSaving/ConsIndShockModel.py), PermGroFac is defined as "Expected permanent income growth factor at the end of this period" (see lines 336-337).  Using your example, PermGroFac[3] should be the expected growth rate from 3 to 4.

**Comment by Mv77** [comment]
Sweet.

Next question then is why HARK asks for n PermGroFac's when the length of life is n periods (my intuition and your conclusion point to (n-1) factors for n periods of life, right?).

So that for 3 periods of life we'd have:
0->PermGroFac[0]->-1->-PermGroFac[1]->-2

Still HARK asks for 3 growth factors in this setting. My guess is that whatever we think is "length of life" is actually "number of non-terminal periods" so that the remaining one applies to the terminal period that we are not counting.

**Comment by Mv77** [comment]
Hypothesis was right. It works now.
