### ISSUE TITLE
Length of life

### ISSUE THREAD

**Issue by Mv77** [matthew-zahn/CGMPort#6]
I have also been sloppy about the total length of life. I have not figured out how HARK handles this.

It receives different parameters:
- T_age: "Age after which simulated agents are automatically killed"
- T_cycle: "Number of periods in the cycle for this agent type"
I don't get the difference between the two.

Also what is the difference between these things and just making SurvProvVec=0 in the last period.

**Comment by matthew-zahn** [comment]
Per Professor Carroll in class: In general, these two variables should be set equal to the max age an agent can attain in the model.

**Comment by Mv77** [comment]
According to https://github.com/econ-ark/HARK/blob/master/HARK/SolvingMicroDSOPs/Calibration/EstimationParameters.py,

It seems that T_cycle is the number of non-terminal periods, and T_age is a period at which agents are automatically killed (at the end of the period). Thus one should set T_age = T_cycle + 1.

This seems to work.
